// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiDtVNe16d3SrfzZsIPwexuv5ubr94ao',
    appId: '1:680251247902:web:6465f7f476007006580d0f',
    messagingSenderId: '680251247902',
    projectId: 'techinterviewchallenge',
    authDomain: 'techinterviewchallenge.firebaseapp.com',
    storageBucket: 'techinterviewchallenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBxPz05fkvmVqwGLPiosiwpPOMrzEnTU',
    appId: '1:680251247902:android:18ce408035951c0d580d0f',
    messagingSenderId: '680251247902',
    projectId: 'techinterviewchallenge',
    storageBucket: 'techinterviewchallenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9LwT2ib-A8xv1x6V3M81xXWr5i23ETxY',
    appId: '1:680251247902:ios:aaa842c241dba767580d0f',
    messagingSenderId: '680251247902',
    projectId: 'techinterviewchallenge',
    storageBucket: 'techinterviewchallenge.appspot.com',
    iosClientId: '680251247902-3ikgn2t2on1cmdt1v5t4jtpdnfgt2mbt.apps.googleusercontent.com',
    iosBundleId: 'ai.axino.techInterviewChallenge',
  );
}
